### ISSUE TITLE
debuff dragging doesn't work

### ISSUE THREAD

**Issue by peterpumpkineater6969** [joelspadin/xivplan#2]
i have no idea if this project is still being maintained but the interface is definitely the most usable and it has more options than raidplan.io but the debuff dragging does not work, trying to drag any debuff onto any party member in the arena doesn't do anything at all

**Comment by joelspadin** [comment]
Yeah. I haven't implemented that part yet, but I left it in because for now it at least allows you to copy the image URLs and then paste them into other objects that support arbitrary images. That's probably my next task whenever I decide to work on this again though.

**Comment by peterpumpkineater6969** [comment]
ah alright, i didn't think about doing it like that, cool. thanks for the update

**Comment by joelspadin** [comment]
Leaving this open in case I ever get around to being able to attach markers to players, but debuffs can be dragged onto the field as separate objects now.

**Comment by joelspadin** [comment]
Closing this and creating a new issue for attaching markers to players.
