### ISSUE TITLE
No status effect are shown

### ISSUE THREAD

**Issue by Cyenia** [joelspadin/xivplan#29]
**Describe the bug**
The XIVAPI search interface is deprecated and is only in maintenance mode. It can happen that the API crashes. In the Discord I was told that if I want stability in the API I should switch to the beta api.
![image](https://github.com/user-attachments/assets/7c1d4bac-8166-4f8e-85ed-ca77bb989f84)

I have looked at the beta and think that these links give the same desired result
https://beta.xivapi.com/api/1/search?query=Name="Slow"&language=en&sheets=Status&fields=Name,Icon,MaxStacks
https://beta.xivapi.com/api/1/asset/ui/icon/015000/015009.tex?format=png

**To Reproduce**
1. Go to Icons > Status effects
2. Search for a status effect

**Expected behavior**
Status effect are shown

**Please complete the following information:**
 - OS: Windows 11 Pro
 - Browser Opera GX
 - Version LVL5 (core: 111.0.5168.54)

**Comment by Cyenia** [comment]
At the moment it's working again because they restarted the API after I asked for it

**Comment by joelspadin** [comment]
f6b9f88bc2e0643dbb8f8fbd112cb7378ffdbebe switches everything to using the beta API.
