### ISSUE TITLE
Add option for specify language for Status search

### ISSUE THREAD

**Issue by Akurosia** [joelspadin/xivplan#5]
It would be nice for not english speaking people to be able to search in theire native language for debuffs (e.g. Astral Fire in German would be "Lichtfeuer")

**Comment by joelspadin** [comment]
Fortunately, XIVAPI provides a language option when searching. I've added a language selection above the search box. If I ever add something else that needs language selection (like localizing the rest of the UI), then that can be moved elsewhere.

**Comment by joelspadin** [comment]
I wasn't really sure whether the language names should be in their respective languages or in English to match the rest of the UI. Let me know if you think I should change that. (The official FFXIV site has everything native except "Japanese" spelled in English...)
