### ISSUE TITLE
Alpha Slider to Color

### ISSUE THREAD

**Issue by Fletch64** [joelspadin/xivplan#7]
Something that would be of great convenience would be an alpha slider, due to the fact that through the use of the hex code, it is possible to modify the alpha of an object, but someone who might not be well versed or aware of this feature might think everything has to be 100% opaque. An alpha slider would help cut down on the time of going to other websites and manually creating the hex code there.

**Comment by joelspadin** [comment]
Nearly all object types that have a color also have an opacity slider. Is there a specific object type that doesn't have it, or is there another reason you're doing this instead of using the slider?

**Comment by Fletch64** [comment]
Ah yeah, one of the main ones was the enemy object, due to things like p10s where the enemy is huge and therefor the line...  An opacity slider is extremely important for that object

**Comment by joelspadin** [comment]
Added an opacity slider to enemy objects. I think that was the only colorable object that didn't have an opacity option, but feel free to reopen this if I missed one.
